name: Test CI

on: [push, pull_request]

jobs:
  test-flake:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Check up flake configuration
        run: nix flake check --all-systems --show-trace

  build-instances:
    strategy:
      fail-fast: false
      matrix:
        instance: [1, 2]

    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build NixOS configuration
        run: nix build .#nixosConfigurations.Kolyma-${{ matrix.instance }}.config.system.build.toplevel --show-trace

  update-merge:
    name: "Dependabot"
    needs: [test-flake, build-instance]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'github-actions[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Enable auto-merge for Update PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.PAT }}
