name: Test CI

on: [push, pull_request]

jobs:
  test-flake:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Check up flake configuration
        run: nix flake check --all-systems --show-trace

  build-instances:
    strategy:
      fail-fast: false
      matrix:
        instance: [1, 2]

    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build NixOS configuration
        run: nix build .#nixosConfigurations.Kolyma-${{ matrix.instance }}.config.system.build.toplevel --show-trace
