name: Update Request CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.PAT }}
          # pr-reviewers: orzklv
          git-author-name: "github-actions[bot]"
          git-author-email: "github-actions[bot]@users.noreply.github.com"
          git-committer-name: "github-actions[bot]"
          git-committer-email: "github-actions[bot]@users.noreply.github.com"

      # - name: Merge
      #   run: gh pr merge --auto "${{ steps.update.outputs.pull-request-number }}" --rebase
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT }}
      #   if: ${{ steps.update.outputs.pull-request-number != '' }}
